#
# requires ../cilium-shared-gateway
#
apiVersion: v1
kind: Namespace
metadata:
  name: keycloak-ns
  labels:
    shared-gateway-access: "true"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak
  namespace: keycloak-ns
spec:
  parentRefs:
  - name: shared-gateway
    namespace: infra-ns
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /auth
    backendRefs:
    - name: keycloak
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak-ns
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - port: 80
      targetPort: 8080
---
#
# kubectl create configmap keycloak-realm --from-file=realm.json=realm-export.json -n keycloak-ns
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          args: ["start-dev", "--import-realm"]
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import
              readOnly: true
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm
            items:
              - key: realm.json
                path: realm.json
