apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-validator.default"
webhooks:
- name: "pod-validator.default.svc.cluster.local"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "default"
      name: "pod-validator"
      path: "/validate"
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lVRkFpajdETTBzbHBqWlBQaUFickV5dlQ2Smlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01qRXdNQzRHQTFVRUF3d25jRzlrTFhaaGJHbGtZWFJ2Y2k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeQpMbXh2WTJGc01CNFhEVEkyTURJd056RTBOVGcwTjFvWERUSTNNREl3TnpFME5UZzBOMW93TWpFd01DNEdBMVVFCkF3d25jRzlrTFhaaGJHbGtZWFJ2Y2k1a1pXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcm10ZjlWZ2ZKYURYSW1SbjNjRWpySEJZa2hyZgptb1J5NFVVRXVjdURQZEIrWkFiSy9XNjVtcllOZ2xMRGN6YnBjKzhjMTR4U2JGcEplM2ZNMGpSQnYwMDJJUmVsCk9raUdadzkwcnZremZmRCt4N1RGYzRIVVhZT2tHeE91cVlHZG1BMHZSS2h1R0U5K3RodG5yU0JOblU1RFpmT3EKRVQzU24vcFMyYzVqQU5LMUtuNW5vcVBvempYakl1dXIycVhUV0o5aGM3T2pvZUR5dUhNQVhWYmExV3dtdEYwSQpQZGlvbDlkYW5YOHh3OEVsM1pjTit3b3dodk93a3ZXRzgydGdzZ21vT1FmSE9aNThaeEtKYnVuZWJxdjd3RW1iCmVJclVoMnJaSnRHNmJ5Q3B0OWU4SXQwTWtYRExZUGtMZUtQc1JEdXFwS3NZSTBVSDMzT1huQjV5VFFJREFRQUIKbzRHWE1JR1VNSE1HQTFVZEVRUnNNR3FDRFhCdlpDMTJZV3hwWkdGMGIzS0NGWEJ2WkMxMllXeHBaR0YwYjNJdQpaR1ZtWVhWc2RJSVpjRzlrTFhaaGJHbGtZWFJ2Y2k1a1pXWmhkV3gwTG5OMlk0SW5jRzlrTFhaaGJHbGtZWFJ2CmNpNWtaV1poZFd4MExuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01CMEdBMVVkRGdRV0JCVC9lRjF0TUJmSUJvQkMKYXBsbDFxRkQ5QkdqM1RBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQW15YkV2eklpMDk4RXptak5LZEhRS3lSbwpxN05RNmE4WHlZNS9Wc2JNenBoTHR3SkdqRUt0ZmtNdHJldkpyMFVqTkIxTDVJZCtEd0hVZTZwTlc5Q3lWQUtQCm9KS2hDdThaUms5clZreEdBWXh0ZFpxNUFYdGdlcVR5dng0VFlHZGNUMENyK2kvS2hwemV0RC83cFh3VzZUVlEKZ2E3Nit0NkNwSmJVazVId2g2NVE4YVlGdnlwL1RvY1dPMDFPbkltYndwU05NMVVSZ2YvVEJqelBzaGIzOHJFMQpHUnZXMVVralQ3NWVKQnRvbEd5SHBFeW51VzFSTFh6QWc3N2lpWG03bkFaZi80bkY2NkFuQVMxZTlsWW4wZWVCCkl2cVAweXhzMThobTV2aUtQOFZpbXNzT09za0ZmWFQ5R0pVUXZmVTduS1kvSk0wV0xiVkRTc2pDZGN0MnZBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5