name: Workflow app1
run-name: executed by ${{ github.actor }}

on:
  push:
    paths:
      - 'src/docker-images/app1/main.py'
      - 'src/docker-images/app1/Dockerfile'
      - 'src/docker-images/app1/requirements.txt'

permissions:
  contents: read
  packages: write

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/weristdominik/app1:latest src/docker-images/app1

      - name: Run container for smoke test
        run: |
          docker run -d --name app1-test -p 5055:5055 -e PORT=5055 -e PREFIX=apptest ghcr.io/weristdominik/app1:latest
          sleep 15
          curl -f http://localhost:5055/apptest || exit 1
          docker stop app1-test
          docker rm app1-test

      - name: Push Docker image
        run: docker push ghcr.io/weristdominik/app1:latest
